### ISSUE TITLE
Migrating doesn't work anymore

### ISSUE THREAD

**Issue by jorenvh** [OnTheGoSystems/migrate-polylang-to-wpml#18]
Hi 

I have a fairly large, complex site that I want to move from WPML to Polylang an Tried your plugin, it says all steps succeed but I can't see my posts anymore in wp-admin after migrating.

Is this plugin still maintained?

thx!

**Comment by kkarpieszuk** [comment]
Yes, it is maintained :) I am sorry it is not working for you. Could you
report it in our forum on https://wpml.org/forums/forum/english-support/
and share a link to the thread here?


--
(en) regards / (pl) pozdrawiam
Konrad Karpieszuk

**Comment by kkarpieszuk** [comment]
Yes, it is maintained :) I am sorry it is not working for you. Could you report it in our forum on https://wpml.org/forums/forum/english-support/ and share a link to the thread here?

**Comment by jorenvh** [comment]
Hi

Apparently I read over the fact that it would create the translation with the locale from Polylang. So the translations where availbel in the databse but had the wrong langauge code. after running some queries on the translation table my posts showed up.

Thx 
Joren

**Comment by kkarpieszuk** [comment]
ok, great that it is fixed now :) If you have any troubles, don't hesitate to report it on our forum :)
