### ISSUE TITLE
`wp_icl_translations` dones't exist

### ISSUE THREAD

**Issue by zslucky** [OnTheGoSystems/migrate-polylang-to-wpml#25]
After I installed and activated the plugin, I got a error `xxxxx.wp_icl_translations` dones't exist, is it a matter? Or how to solve it?

**Comment by brucepearson** [comment]
@zslucky I think you need to activate the WPML core plugin too. See installation instructions here - https://github.com/OnTheGoSystems/migrate-polylang-to-wpml

**Comment by zslucky** [comment]
thansk @brucepearson
